
apiVersion: v1
kind: Service
metadata:
  labels:
    app: restapi
  name: restapi
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30301
  selector:
    app: restapi
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: restapi
  name: restapi
spec:
  selector:
    matchLabels:
      app: restapi
  template:
    metadata:
      labels:
        app: restapi
    spec:
      containers:
      - image: docker.io/library/restapi:latest
        imagePullPolicy: Never
        name: restapi
        resources:
          limits:
            cpu: "0.2"
            memory: 200Mi
        ports:
          - containerPort: 8000
        env:
         - name: MONGOURI
           value: "mongodb://golangAPI:123abc@mongodb-service/golangAPI"
      restartPolicy: Always
