
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webui
  name: webui
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30300
  selector:
    app: webui
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webui
  name: webui
spec:
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - image: docker.io/library/webui:latest
        imagePullPolicy: Never
        name: webui
        resources:
          limits:
            cpu: "0.2"
            memory: 200Mi
        ports:
          - containerPort: 80
      restartPolicy: Always
